// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYsSmJjio9WpWL0Zy6mggpJkryZlpz44c',
    appId: '1:450436408734:web:af0fb94ca3271d2bb7628f',
    messagingSenderId: '450436408734',
    projectId: 'novelnest-827a6',
    authDomain: 'novelnest-827a6.firebaseapp.com',
    storageBucket: 'novelnest-827a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6bZN8lbHaS41jpCs8IVLbVymgq6-UbTA',
    appId: '1:450436408734:android:7f8539764afef50db7628f',
    messagingSenderId: '450436408734',
    projectId: 'novelnest-827a6',
    storageBucket: 'novelnest-827a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiwhE0l5gQRoYlfkD3pEluOFpmKBH4uL8',
    appId: '1:450436408734:ios:6b6d7651ffb16e92b7628f',
    messagingSenderId: '450436408734',
    projectId: 'novelnest-827a6',
    storageBucket: 'novelnest-827a6.appspot.com',
    androidClientId: '450436408734-c9vdjvqlpn2smntjqskccbuchn2gavv6.apps.googleusercontent.com',
    iosClientId: '450436408734-dd05262nsuvet0h30k4jpa1jfk0uill8.apps.googleusercontent.com',
    iosBundleId: 'com.cliffhanger.barter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiwhE0l5gQRoYlfkD3pEluOFpmKBH4uL8',
    appId: '1:450436408734:ios:6b6d7651ffb16e92b7628f',
    messagingSenderId: '450436408734',
    projectId: 'novelnest-827a6',
    storageBucket: 'novelnest-827a6.appspot.com',
    androidClientId: '450436408734-c9vdjvqlpn2smntjqskccbuchn2gavv6.apps.googleusercontent.com',
    iosClientId: '450436408734-dd05262nsuvet0h30k4jpa1jfk0uill8.apps.googleusercontent.com',
    iosBundleId: 'com.cliffhanger.barter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYsSmJjio9WpWL0Zy6mggpJkryZlpz44c',
    appId: '1:450436408734:web:e93d5635985068b9b7628f',
    messagingSenderId: '450436408734',
    projectId: 'novelnest-827a6',
    authDomain: 'novelnest-827a6.firebaseapp.com',
    storageBucket: 'novelnest-827a6.appspot.com',
  );

}